### ISSUE TITLE
 Node Engine

### ISSUE THREAD

**Issue by Nathanofzion** [kalepail/soroban-passkey#1]
Could you please specify node -v in Package.json.
Thank you

**Comment by kalepail** [comment]
Resolved in https://github.com/kalepail/soroban-passkey/commit/96bf315c45d8a4cebdb06a9ec06da9e1ea537c3b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R54
